export class AcrmError extends Error {
  constructor(message: string, public code: string) {
    super(message);
    this.name = "AcrmError";
  }
}

export const ERR = {
  NO_WORKSPACE: "ACRM_ERROR_NO_WORKSPACE",
  WORKSPACE_EXISTS: "ACRM_ERROR_WORKSPACE_EXISTS",
  NOT_FOUND: "ACRM_ERROR_NOT_FOUND",
  INVALID_INPUT: "ACRM_ERROR_INVALID_INPUT",
  UNIQUE_VIOLATION: "ACRM_ERROR_UNIQUE_VIOLATION",
  MERGE_CONFLICT: "ACRM_ERROR_MERGE_CONFLICT",
  WRITE_REJECTED: "ACRM_ERROR_WRITE_REJECTED",
  EXECUTE: "ACRM_ERROR_EXECUTE",
  IMPORT: "ACRM_ERROR_IMPORT",
  INIT: "ACRM_ERROR_INIT",
  UNHANDLED: "ACRM_ERROR_UNHANDLED",
} as const;
