export const AGENT_INSTRUCTION_FILENAMES = ["CLAUDE.md", "AGENTS.md"] as const;
export const AGENT_INSTRUCTIONS_START = "<!-- agent-crm-app:start -->";
export const AGENT_INSTRUCTIONS_END = "<!-- agent-crm-app:end -->";

export const AGENT_INSTRUCTIONS_COVERED_COMMANDS = [
  "init",
  "connect",
  "connect linkedin",
  "import",
  "import csv",
  "import gmail",
  "import linkedin",
  "import x",
  "import post",
  "import transcript",
  "execute",
  "records",
  "records create",
  "records update",
  "records dedupe",
  "object",
  "object create",
  "attribute",
  "attribute add",
  "attribute edit-options",
  "signals",
  "signals list",
  "signals sync",
  "signals run",
  "skills",
  "skills install",
  "skills list",
  "skills remove",
  "auth",
] as const;

export const AGENT_INSTRUCTIONS_BLOCK = [
  AGENT_INSTRUCTIONS_START,
  "## Agent CRM Workspace",
  "",
  "This directory is managed by Agent CRM. The `.acrm` file is the portable CRM database for this workspace.",
  "",
  "Before using `acrm`, Agent CRM skills, or any local `.acrm` workflow:",
  "- Use the installed `acrm` directly; do not spend agent turns checking the latest CLI version unless the user explicitly asks.",
  "- If `acrm` is missing or a command reports that the CLI must be updated, tell the user the exact failure and ask them to install or update `@agent-crm/cli`.",
  "",
  "Fast orientation:",
  "- `acrm` is a headless CRM for AI agents. It stores people, companies, deals, LinkedIn/X posts, meeting transcripts, email threads, and email messages in a local `.acrm` file.",
  "- The CLI resolves the workspace by walking up from the current directory. Use `acrm -w /path/to/workspace.acrm ...` when you need to target a specific file.",
  "- Prefer first-class CLI commands for common writes. Use `acrm execute` for inspection, reporting, or custom SQL when the CLI does not expose the exact operation.",
  "",
  "Common commands:",
  "- `acrm connect linkedin` connects LinkedIn through Agent CRM's hosted sync engine, or reports when the workspace is already connected. `acrm connect linkedin --status` checks status without starting a connect flow.",
  "- `acrm import csv ./leads.csv` imports people and companies from a CSV. It creates deals only when deal columns such as `deal_name` or `deal` are present.",
  "- `acrm import gmail` connects Gmail through Agent CRM's hosted sync engine and syncs people, email threads, and email messages.",
  "- For Gmail CRM imports, ask for a backfill window and newsletter filtering before OAuth. Use `acrm import gmail --backfill-days 30 --exclude-newsletters`, `--backfill-days 90`, or `--backfill-since YYYY-MM-DD`; use `--include-newsletters` only when the user wants marketing/newsletter mail in the CRM.",
  "- `acrm import linkedin` imports existing contacts from the connected LinkedIn account, then starts hosted LinkedIn message-history backfill in the background. `acrm import linkedin --sync` imports already-stored LinkedIn messages from the hosted sync engine into the local workspace.",
  "- `acrm import linkedin <profile-url-or-slug>` imports one LinkedIn profile, upserts the person, and links their current employer as a company. Requires `APIFY_API_TOKEN` in `.env`.",
  "- `acrm import x <handle-or-url>` imports one X/Twitter profile. Requires `APIFY_API_TOKEN` in `.env`; if the result says `needs_enrichment`, run the `enrich-x-bio` skill.",
  "- `acrm import post <linkedin-or-x-post-url>` imports a LinkedIn or X post, upserts the author as a person, stores the post, and links them.",
  "- `acrm auth <provider>` caches OAuth credentials for transcript providers before using `acrm import transcript --from <provider>`.",
  "- `acrm import transcript --from <provider> <meeting-id>` imports a meeting transcript from an authenticated provider; `acrm import transcript --file <file>` or stdin accepts canonical transcript JSON.",
  "- `acrm records create <object> --field slug=value` creates one record on a built-in or custom object.",
  "- `acrm records update <object> <record_id> --field slug=value` updates an existing record; repeat `--field` for multiple or multivalued fields.",
  "- `acrm records dedupe <object> --keep <record_id> --discard <record_id>` merges duplicate records.",
  "- `acrm execute --schema` dumps the current EAV layout: objects, attributes, types, and config.",
  "- `acrm execute '<sql>' '[params]'` runs SQL or mutations against the workspace. Single-quote SQL that contains `$1`, `$2`, etc. so the shell does not expand placeholders.",
  "",
  "Data model and SQL:",
  "- Storage is EAV, not one SQL table per object. There are no per-object tables such as `people`, `companies`, `deals`, `posts`, `transcripts`, or `communication_messages`.",
  "- Query `acrm_record` for records, `acrm_attribute` for field definitions, and `acrm_value` for field values.",
  "- Current values require `active_until IS NULL`; historical values remain in `acrm_value` with a non-null `active_until`.",
  "- For record references, prefer indexed `ref_object` and `ref_record_id` columns instead of digging into `value_json`.",
  "- The SQL engine is DataFusion, not SQLite/Postgres. Use `$1` placeholders, `information_schema` for introspection, and `lix_json_get_text` or `lix_json_get` for JSON columns.",
  "- Common JSON value keys: text/url/number use `value`; date uses `date`; timestamp uses `timestamp`; personal-name uses `full_name`; email-address uses `email_address`; phone-number uses `phone_number`; domain uses `domain`; status/select use `id` and `title`; currency uses `currency_value` and `currency_code`.",
  "",
  "Built-in objects:",
  "- `people`: contacts identified by email address, LinkedIn URL, X/Twitter URL, or phone.",
  "- `companies`: organizations identified by domain.",
  "- `deals`: sales opportunities. Do not coerce hiring, fundraising, projects, or other workflows into deals; `deals.stage` is a sales pipeline enum.",
  "- `posts`: LinkedIn/X posts linked to their author via `posts.author` and `people.associated_posts`.",
  "- `transcripts`: meeting/call transcripts linked to attendees via `transcripts.participants` and `people.associated_transcripts`.",
  "- `communication_threads` and `communication_messages`: synced email/LinkedIn conversations linked to participants.",
  "",
  "Custom schema:",
  "- `acrm object create candidates` registers a new object.",
  "- `acrm attribute add candidates.stage --type status --option sourced --option screen --option onsite --option offer` adds a status field.",
  "- `acrm attribute add candidates.applied_for --type record-reference --target-object deals` adds a relationship field.",
  "- `acrm attribute edit-options deals.stage add custom_value` extends a built-in enum when that is genuinely the right object.",
  "",
  "Signals and skills:",
  "- Local signals live in `<workspace>/signals/*.md`. Use `acrm signals list`, `acrm signals sync`, and `acrm signals run` to inspect, create output attributes, and fill missing people/company fields.",
  "- `acrm skills install` installs bundled Agent CRM skills into supported AI agents; `acrm skills list` shows what is installed; `acrm skills remove` removes installed Agent CRM skills.",
  "- Useful bundled skills include `acrm-query`, `acrm-onboarding`, `create-signals`, `follow-up`, `prep-call`, `post-call`, `setup-transcripts`, and `import-post`.",
  AGENT_INSTRUCTIONS_END,
  "",
].join("\n");

export const AGENT_WORKSPACE_INSTRUCTIONS = {
  filenames: AGENT_INSTRUCTION_FILENAMES,
  startMarker: AGENT_INSTRUCTIONS_START,
  endMarker: AGENT_INSTRUCTIONS_END,
  block: AGENT_INSTRUCTIONS_BLOCK,
  coveredCommands: AGENT_INSTRUCTIONS_COVERED_COMMANDS,
} as const;
