export const AGENT_INSTRUCTION_FILENAMES = ["CLAUDE.md", "AGENTS.md"] as const;
export const AGENT_INSTRUCTIONS_START = "<!-- agent-crm-app:start -->";
export const AGENT_INSTRUCTIONS_END = "<!-- agent-crm-app:end -->";

export const AGENT_INSTRUCTIONS_COVERED_COMMANDS = [
  "init",
  "connect",
  "connect linkedin",
  "connect granola",
  "import",
  "import csv",
  "import gmail",
  "import granola",
  "import linkedin",
  "import x",
  "import post",
  "import transcript",
  "records",
  "records create",
  "records update",
  "records dedupe",
  "deals",
  "deals list",
  "deals show",
  "deals create",
  "deals update",
  "deals delete",
  "deals pipeline",
  "deals pipeline list",
  "deals pipeline context",
  "deals pipeline set",
  "object",
  "object create",
  "attribute",
  "attribute add",
  "attribute edit-options",
  "signals",
  "signals list",
  "signals sync",
  "signals run",
  "skills",
  "skills install",
  "skills list",
  "skills remove",
] as const;

export const AGENT_INSTRUCTIONS_BLOCK = [
  AGENT_INSTRUCTIONS_START,
  "## Agent CRM Workspace",
  "",
  "This directory is managed by Agent CRM. In the desktop app, Agent CRM uses a hosted cloud workspace from the signed-in account. Standalone CLI usage can still target Neon, Supabase, or another Postgres-compatible database.",
  "",
  "Before using `acrm`, Agent CRM skills, or any workspace workflow:",
  "- Use the installed `acrm` directly; do not spend agent turns checking, comparing, or updating CLI versions unless the user explicitly asks.",
  "- If `acrm` is missing, tell the user the exact failure and ask them to install `@agent-crm/cli`.",
  "",
  "Fast orientation:",
  "- `acrm` is a headless CRM for AI agents. It stores people, companies, deals, LinkedIn/X posts, meeting transcripts, email threads, and email messages.",
  "- In the desktop app, use the existing `ACRM_SYNC_ENGINE_URL`, `ACRM_CLOUD_WORKSPACE_ID`, `ACRM_CLOUD_ORG_ID`, and `ACRM_DESKTOP_SESSION_TOKEN` environment. Do not print `ACRM_DESKTOP_SESSION_TOKEN`.",
  "- Outside the desktop app, target a workspace with `acrm -w <postgres-url> ...`, or set `ACRM_DATABASE_URL`, `NEON_DATABASE_URL`, `SUPABASE_DATABASE_URL`, or `DATABASE_URL`. Use `ACRM_DATABASE_PROVIDER=neon|supabase|postgres` only when the provider cannot be inferred from the URL.",
  "- Use first-class CLI commands for reads and writes. Direct SQL/raw workspace queries are not supported in cloud-first Agent CRM workspaces.",
  "",
  "Common commands:",
  "- `acrm connect linkedin` connects LinkedIn through Agent CRM's hosted sync engine, or reports when the workspace is already connected. `acrm connect linkedin --status` checks status without starting a connect flow.",
  "- `acrm connect granola` connects Granola through Agent CRM's hosted sync engine. Use `--api-key-stdin` when an agent skill has collected the user's Granola API key.",
  "- `acrm import csv ./leads.csv` imports people and companies from a CSV. It creates deals only when deal columns such as `deal_name` or `deal` are present.",
  "- `acrm import gmail` connects Gmail through Agent CRM's hosted sync engine and syncs people, email threads, and email messages. In desktop sessions it reuses the app login through a short-lived browser handoff.",
  "- For Gmail CRM imports, ask for a backfill window and newsletter filtering before OAuth. Use `acrm import gmail --backfill-days 30 --exclude-newsletters`, `--backfill-days 90`, or `--backfill-since YYYY-MM-DD`; use `--include-newsletters` only when the user wants marketing/newsletter mail in the CRM.",
  "- `acrm import granola` imports synced Granola transcripts into `transcripts`, creates/links attendees as `people`, and supports `--cutoff-date <YYYY-MM-DD>` for recency-limited backfills.",
  "- `acrm import linkedin` imports existing contacts from the connected LinkedIn account, then starts scoped hosted LinkedIn message-history backfill for those contacts in the background. Do not run `acrm import linkedin --sync` in the normal import flow.",
  "- `acrm import linkedin <profile-url-or-slug>` imports one LinkedIn profile, upserts the person, and links their current employer as a company. Requires `APIFY_API_TOKEN` in `.env`.",
  "- `acrm import x <handle-or-url>` imports one X/Twitter profile. Requires `APIFY_API_TOKEN` in `.env`; if the result says `needs_enrichment`, run the `enrich-x-bio` skill.",
  "- `acrm import post <linkedin-or-x-post-url>` imports a LinkedIn or X post, upserts the author as a person, stores the post, and links them.",
  "- `acrm import transcript --file <file>` or stdin accepts canonical transcript JSON for manual/provider-specific transcript imports.",
  "- `acrm records create <object> --field slug=value` creates one record on a built-in or custom object.",
  "- `acrm records update <object> <record_id> --field slug=value` updates an existing record; repeat `--field` for multiple or multivalued fields.",
  "- `acrm records dedupe <object> --keep <record_id> --discard <record_id>` merges duplicate records.",
  "- In desktop cloud sessions, `acrm deals pipeline set --stage lead:Lead --stage closed_won:\"Closed Won\" --stage closed_lost:\"Closed Lost\"` configures the Deals pipeline.",
  "- In desktop cloud sessions, `acrm deals create`, `acrm deals update`, `acrm deals list`, and `acrm deals delete` manage sales opportunities through the hosted backend API.",
  "",
  "Data model:",
  "- Storage is EAV, not one SQL table per object. There are no per-object tables such as `people`, `companies`, `deals`, `posts`, `transcripts`, or `communication_messages`.",
  "- Built-in and custom CRM objects are represented by object slugs, attributes, records, and values. Prefer `acrm records`, `acrm object`, `acrm attribute`, import commands, or sync-engine REST APIs over direct database access.",
  "- Current values require `active_until IS NULL`; historical values remain in `acrm_value` with a non-null `active_until`.",
  "- Record-reference fields store links between object records. Use `<slug>=<target_object>:<target_record_id>` with `acrm records create` or `acrm records update`.",
  "",
  "Built-in objects:",
  "- `people`: contacts identified by email address, LinkedIn URL, X/Twitter URL, or phone.",
  "- `companies`: organizations identified by domain.",
  "- `deals`: sales opportunities. Do not coerce hiring, fundraising, projects, or other workflows into deals; `deals.stage` is a sales pipeline enum.",
  "- `posts`: LinkedIn/X posts linked to their author via `posts.author` and `people.associated_posts`.",
  "- `transcripts`: meeting/call transcripts linked to attendees via `transcripts.participants` and `people.associated_transcripts`.",
  "- `communication_threads` and `communication_messages`: synced email/LinkedIn conversations linked to participants.",
  "",
  "Custom schema:",
  "- `acrm object create candidates` registers a new object.",
  "- `acrm attribute add candidates.stage --type status --option sourced --option screen --option onsite --option offer` adds a status field.",
  "- `acrm attribute add candidates.applied_for --type record-reference --target-object deals` adds a relationship field.",
  "- `acrm attribute edit-options deals.stage add custom_value` extends a built-in enum when that is genuinely the right object.",
  "",
  "Signals and skills:",
  "- Local signals live in `signals/*.md` under the current project directory. Use `acrm signals list`, `acrm signals sync`, and `acrm signals run` to inspect, create output attributes, and fill missing people/company fields.",
  "- `acrm skills install` installs bundled Agent CRM skills into supported AI agents; `acrm skills list` shows what is installed; `acrm skills remove` removes installed Agent CRM skills.",
  "- Useful bundled skills include `acrm-onboarding`, `setup-deal-pipeline`, `connect-granola-to-acrm`, `create-signals`, and `import-post`.",
  AGENT_INSTRUCTIONS_END,
  "",
].join("\n");

export const AGENT_WORKSPACE_INSTRUCTIONS = {
  filenames: AGENT_INSTRUCTION_FILENAMES,
  startMarker: AGENT_INSTRUCTIONS_START,
  endMarker: AGENT_INSTRUCTIONS_END,
  block: AGENT_INSTRUCTIONS_BLOCK,
  coveredCommands: AGENT_INSTRUCTIONS_COVERED_COMMANDS,
} as const;
